### PR TITLE
Two more checks for PC metrics

### PR DESCRIPTION
**Pull request by mmyros**
`Not all labels are this cluster` and `No fewer than 20 spikes in this cluster`

### CODE REVIEW

**Comment by jsiegle** [comment]
Looks good, thanks for updating the travis file!

**Comment by mmyros** [comment]
Oops sorry did not mean to pshh travis, since it doesn't seem to run properly still. It may be easier to debug further though with the modifications I made...

**Comment by jsiegle** [comment]
No worries. The tests were originally designed to use a local data cache, which is no longer working. The tests are in need of a complete overhaul, and it will be easier to debug with the simpler config file you wrote.

**Comment by jsiegle** [comment]
I just pushed some additional changes and the tests are running successfully now (albeit without any actual content).

**Comment by mmyros** [comment]
Nice, happy to help!

**Pull request merged**
